apiVersion: v1
kind: Namespace
metadata:
  name: juice-shop-internal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-internal
  namespace: juice-shop-internal
spec:
  selector:
    matchlabels:
      app: juice-shop-internal
  template:
    metadata:
      labels:
        app: juice-shop-internal
    spec:
      containers:
      - name: juice-shop-internal
        image: iuriikogan/snyk-juice-shop:linux-arm64
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
