apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-goof 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-goof 
  namespace: nodejs-goof 
spec:
  selector:
    matchLabels:
      app: nodejs-goof 
  template:
    metadata:
      labels:        
        app: nodejs-goof 
    spec:
      containers:
      - name: nodejs-goof 
        image: iuriikogan/nodejs-goof:linux-arm64
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-goof 
  labels:
    app: nodejs-goof 
spec:
  type: ClusterIP
  ports:
    - port: 1337
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-goof 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  nodejs-goof-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-goof 
            port:
              number: 1337
