name: Snyk Scan

on:
  workflow_dispatch:
  pull_request:
    branches: main
env:
  IMAGE_NAME: nodejs-goof
  
jobs:
  build:
    name: Snyk Scan 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Build project
        run: npm ci --legacy-peer-deps
  
      - name: Setup Snyk + snyk-filter # For information about the required commands https://docs.snyk.io/scm-ide-and-ci-cd-integrations/snyk-ci-cd-integrations
        run: |
          npm install snyk snyk-filter -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source
        run: snyk test --json --print-deps | snyk-delta --setPassIfNoBaseline true
        # run: snyk monitor --org=XXX ---project-name=XXX - Use snyk monitor command to upload the results to the UI
        continue-on-error: true

      - name: Snyk Code
        run: snyk code test
        continue-on-error: true